// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9VMZ9p0dcNalo9vZildhuwXRvjDAChbs',
    appId: '1:674257205132:web:38298e6d795f028fb048a9',
    messagingSenderId: '674257205132',
    projectId: 'barterio-9859f',
    authDomain: 'barterio-9859f.firebaseapp.com',
    storageBucket: 'barterio-9859f.appspot.com',
    measurementId: 'G-Y7KWYHVZW9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccGUtAn3QJrMLMguRFJ73go-9e5luaDE',
    appId: '1:674257205132:ios:55c878f1db02a120b048a9',
    messagingSenderId: '674257205132',
    projectId: 'barterio-9859f',
    storageBucket: 'barterio-9859f.appspot.com',
    iosClientId: '674257205132-pectgloj6ufggvrn67phvo0l4veru026.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
